// This file was generated by RedwoodJS
import FatalErrorPageType from 'C:/Users/fletchen24/Programming/FBLA/2022-23/FBLA-Redwood/src/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from 'C:/Users/fletchen24/Programming/FBLA/2022-23/FBLA-Redwood/src/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}
